dist: trusty
sudo: required

language: perl6

perl6:
    - 2017.01
    - latest

install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libopencv-dev
    - rakudobrew build zef

script:
    - zef build .
    - prove -e "perl6 -Ilib"
