language: perl6

dist: trusty

perl6:
    - 2015.12
    - latest

install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libopencv-dev
    - rakudobrew build-panda
    - panda install LibraryMake

script: panda-build && prove -e perl6 t
